def raise_exception(error_message):
    raise Exception(error_message)